-- This migration is now obsolete. MaterialVersion has been removed from the domain and DB.
-- The table material_version is no longer needed.
-- (If you need to drop the table, do it in a new migration, not here.)
